import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState } from "../../app/store";
import { generateOtp, validateOtp } from "./loginAPI";

export interface LoginState {
  value: number;
  status: "idle" | "loading" | "failed";
}

const initialState: LoginState = {
  value: 0,
  status: "idle",
};

export const generateOtpAsync = createAsyncThunk(
  "login/generateOtp",
  async (mobileNumber: number) => {
    const response = await generateOtp(mobileNumber);
    return response.data;
  }
);

export const validateOtpAync = createAsyncThunk(
  "login/validateOtp",
  async (action: any) => {
    const response = await validateOtp(action.mobileNumber, action.otp);
    return response.data;
  }
);

export const loginSlice = createSlice({
  name: "login",
  initialState,
  reducers: {
    increment: (state) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.value += 1;
    },
    decrement: (state) => {
      state.value -= 1;
    },
    // Use the PayloadAction type to declare the contents of `action.payload`
    incrementByAmount: (state, action: PayloadAction<number>) => {
      state.value += action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(generateOtpAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(generateOtpAsync.fulfilled, (state, action) => {
        state.status = "idle";
        state.value += action.payload;
      })
      .addCase(validateOtpAync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(validateOtpAync.fulfilled, (state, action) => {
        state.status = "idle";
        state.value += action.payload;
      });
  },
});

export const { increment, decrement, incrementByAmount } = loginSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectCount = (state: RootState) => state.counter.value;

export default loginSlice.reducer;
